#ifndef __SMARTHOME_H_
#define __SMARTHOME_H_
#define ENDPOINT_ID_SMARTHOME 0X01
#define PROFILE_ID_SMARTHOME 0X501
#define DEVICE_ID_COORDINATOR 0X01
#define DEVICE_ID_SDEVICE 0X02
#define DEVIDE_VERSION_ID 0X0

#define JOINNET_CMD_ID 0X11
#define TOGGLE_CMD_ID  0X12
#define HEART_BEAT_CMD_ID  0X13
#define MSG_CMD_ID 0x14
#define  HEART_BEAT_MAX_COUNT 3


#define TIMER_TIMEOUT_EVT 0X01
#define SEND_TIMER_EVT 0x02
#endif